
services:
  db:
    image: postgres:16
    container_name: veterinaria_pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppwd
      POSTGRES_DB: veterinaria
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d veterinaria"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pg_data:
