version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: veterinario_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: veterinario
      MYSQL_USER: app
      MYSQL_PASSWORD: apppwd
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpwd"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: nginx:alpine
    container_name: veterinario_nginx
    ports:
      - "8080:80"          # Frontend React ya construido
    volumes:
      - ./build:/usr/share/nginx/html

  tomcat:
    image: tomcat:10.1-jdk17
    container_name: veterinario_tomcat
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"        # Tomcat disponible en http://localhost:8081
    environment:
      TZ: America/Mexico_City
      # Variables que tu app Java puede leer
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: veterinario
      DB_USER: app
      DB_PASS: apppwd
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./tomcat/lib/mysql-connector-j-8.4.0.jar:/usr/local/tomcat/lib/mysql-connector-j-8.4.0.jar:ro
    restart: always

volumes:
  db_data:


